DROP TABLE IF EXISTS pm_site;

DROP TABLE IF EXISTS pm_url;

DROP TABLE IF EXISTS pm_template_data;

DROP TABLE IF EXISTS pm_user;

DROP TABLE IF EXISTS pm_role;

DROP TABLE IF EXISTS pm_user_role;

DROP TABLE IF EXISTS pm_permission;

DROP TABLE IF EXISTS pm_session;
